<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>unggah_dokumen</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>eccca3a1-923a-45ed-8da1-0756066ce094</testSuiteGuid>
   <testCaseLink>
      <guid>e4a8b20b-4567-49f0-bc22-c270699d0fa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/profil/unggah_dokumen</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>892defd6-27e8-4308-a690-5ed60c4cb1f2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/unggah_dokumen/unggah_dokumen</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>892defd6-27e8-4308-a690-5ed60c4cb1f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>keterangan</value>
         <variableId>b8358f92-60cc-46ed-8e52-005d6dacdfa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>892defd6-27e8-4308-a690-5ed60c4cb1f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nama_foto</value>
         <variableId>21bf81e0-fecd-4fd7-bb58-a27f2fbef854</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>892defd6-27e8-4308-a690-5ed60c4cb1f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>e0b32713-6db3-4457-adba-c9e9ab06c4ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17d3178e-06f1-4308-971c-8a5c2655bdca</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
